using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;

// è¿™ä¸ªç±»æ˜¯ç®¡ç†å…‰æ ‡çš„ï¼Œå’Œæ¨¡å‹æ— å…³å‘ƒå‘ƒå‘ƒ
public class PlacementIndicator : MonoBehaviour
{

    private ARRaycastManager _rayManager;
    [SerializeField]
    private GameObject visual;

    private bool _isPrefabAlreadyPlaced = false;

    void Start()
    {
        // get the components
        _rayManager = FindObjectOfType<ARRaycastManager>();
        visual = transform.GetChild(0).gameObject;

        // hide the placement indicator visual
        visual.SetActive(false);
    }

    void Update()
    {
        // shoot a raycast from the center of the screen
        // if (_isPrefabAlreadyPlaced) return;
        var hits = new List<ARRaycastHit>();
        _rayManager.Raycast(new Vector2(Screen.width / 2, Screen.height / 2), hits, TrackableType.Planes);

        // if we hit an AR plane surface, update the position and rotation
        
        // åªå…è®¸æ›´æ”¹ä¸€æ¬¡ä½ç½®
        // TODO: ğŸ‘†ğŸ»å¥½åƒæ²¡ç”¨
        // TODO: ç”¨visual.activeSelfç¦æ‰ä¹Ÿæ²¡ç”¨ï¼Œå†ç‚¹å‡»å±å¹•é‡Œä»»æ„åœ°æ–¹è¿˜æ˜¯ä¼šå‡ºç°æ–°æ¨¡å‹ã€‚
        if (hits.Count > 0)
        {
            transform.position = hits[0].pose.position;
            transform.rotation = hits[0].pose.rotation;
            // _isPrefabAlreadyPlaced = true;
            
            // enable the visual if it's disabled
            if (!visual.activeInHierarchy)
                visual.SetActive(true);
        }
    }
}